SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `GVF_DB_Variant` DEFAULT CHARACTER SET latin1 ;
USE `GVF_DB_Variant` ;

-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`INDIVIDUAL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`INDIVIDUAL` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `dbxref` VARCHAR(50) NULL DEFAULT NULL ,
  `Gender` VARCHAR(7) NULL DEFAULT NULL ,
  `Population` VARCHAR(50) NULL DEFAULT NULL ,
  `Comment` VARCHAR(50) NULL DEFAULT NULL ,
  `GenomeAnnotation` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`GENOMESCOPE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`GENOMESCOPE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SourceMethod` VARCHAR(50) NULL DEFAULT NULL ,
  `TechnologyPlatform` VARCHAR(50) NULL DEFAULT NULL ,
  `ScoreMethod` VARCHAR(50) NULL DEFAULT NULL ,
  `GenomicSource` VARCHAR(50) NULL DEFAULT NULL ,
  `INDIVIDUAL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_GENOMESCOPE_INDIVIDUAL1` (`INDIVIDUAL_ID` ASC) ,
  CONSTRAINT `fk_GENOMESCOPE_INDIVIDUAL1`
    FOREIGN KEY (`INDIVIDUAL_ID` )
    REFERENCES `GVF_DB_Variant`.`INDIVIDUAL` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`VARIANT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`VARIANT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `FileID` VARCHAR(50) NOT NULL ,
  `Source` VARCHAR(50) NOT NULL ,
  `Type` VARCHAR(50) NOT NULL ,
  `Start` INT(11) NOT NULL ,
  `End` INT(11) NOT NULL ,
  `Score` FLOAT NOT NULL ,
  `Strand` VARCHAR(50) NOT NULL ,
  `dbxref` VARCHAR(50) NULL DEFAULT NULL ,
  `ReferenceSequence` VARCHAR(50) NULL DEFAULT NULL ,
  `TotalReads` INT(11) NULL DEFAULT NULL ,
  `Alias` VARCHAR(50) NULL DEFAULT NULL ,
  `Zygosity` VARCHAR(50) NULL DEFAULT NULL ,
  `VariantSequence` VARCHAR(50) NULL ,
  `VariantReads` VARCHAR(50) NULL ,
  `INDIVIDUAL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_VARIANT_INDIVIDUAL1` (`INDIVIDUAL_ID` ASC) ,
  CONSTRAINT `fk_VARIANT_INDIVIDUAL1`
    FOREIGN KEY (`INDIVIDUAL_ID` )
    REFERENCES `GVF_DB_Variant`.`INDIVIDUAL` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`GENOMEVARIANTRELATION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`GENOMEVARIANTRELATION` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `VARIANT_ID` BIGINT(20) NOT NULL ,
  `GENOMESCOPE_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_GENOMEVARIANTRELATION_VARIANT1` (`VARIANT_ID` ASC) ,
  INDEX `fk_GENOMEVARIANTRELATION_GENOMESCOPE1` (`GENOMESCOPE_ID` ASC) ,
  CONSTRAINT `fk_GENOMEVARIANTRELATION_VARIANT1`
    FOREIGN KEY (`VARIANT_ID` )
    REFERENCES `GVF_DB_Variant`.`VARIANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GENOMEVARIANTRELATION_GENOMESCOPE1`
    FOREIGN KEY (`GENOMESCOPE_ID` )
    REFERENCES `GVF_DB_Variant`.`GENOMESCOPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`INDIVIDUALPHENOTYPE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`INDIVIDUALPHENOTYPE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `Phenotype` VARCHAR(50) NULL DEFAULT NULL ,
  `INDIVIDUAL_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_INDIVIDUALPHENOTYPE_INDIVIDUAL1` (`INDIVIDUAL_ID` ASC) ,
  CONSTRAINT `fk_INDIVIDUALPHENOTYPE_INDIVIDUAL1`
    FOREIGN KEY (`INDIVIDUAL_ID` )
    REFERENCES `GVF_DB_Variant`.`INDIVIDUAL` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`THOUSANDGENOMES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`THOUSANDGENOMES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `GenomeLocation` VARCHAR(50) NOT NULL ,
  `Dbsnpid` VARCHAR(50) NULL DEFAULT NULL ,
  `ReferenceAllele` VARCHAR(50) NULL DEFAULT NULL ,
  `ReferenceStat` FLOAT NULL DEFAULT NULL ,
  `VariantAllele` VARCHAR(50) NULL DEFAULT NULL ,
  `VariantFrequency` FLOAT NULL DEFAULT NULL ,
  `Individual_Id` INT NOT NULL ,
  `VARIANT_ID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_THOUSANDGENOMES_VARIANT1` (`VARIANT_ID` ASC) ,
  CONSTRAINT `fk_THOUSANDGENOMES_VARIANT1`
    FOREIGN KEY (`VARIANT_ID` )
    REFERENCES `GVF_DB_Variant`.`VARIANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`VARIANTEFFECT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`VARIANTEFFECT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `FeatureID` VARCHAR(50) NULL DEFAULT NULL ,
  `VariantEffect` VARCHAR(50) NULL DEFAULT NULL ,
  `FeatureAffected` VARCHAR(50) NULL DEFAULT NULL ,
  `NcbiRefSeq` VARCHAR(50) NULL DEFAULT NULL ,
  `VARIANT_ID` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_VARIANTEFFECT_VARIANT1` (`VARIANT_ID` ASC) ,
  CONSTRAINT `fk_VARIANTEFFECT_VARIANT1`
    FOREIGN KEY (`VARIANT_ID` )
    REFERENCES `GVF_DB_Variant`.`VARIANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`SAMPLE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`SAMPLE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `INDIVIDUAL_ID` INT(11) NOT NULL ,
  `SampleName` VARCHAR(45) NULL DEFAULT NULL ,
  `SampleId` INT NOT NULL ,
  `TumorId` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SAMPLE_INDIVIDUAL1` (`INDIVIDUAL_ID` ASC) ,
  CONSTRAINT `fk_SAMPLE_INDIVIDUAL1`
    FOREIGN KEY (`INDIVIDUAL_ID` )
    REFERENCES `GVF_DB_Variant`.`INDIVIDUAL` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GVF_DB_Variant`.`COSMIC`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `GVF_DB_Variant`.`COSMIC` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `Version` VARCHAR(10) NOT NULL ,
  `GeneName` VARCHAR(45) NULL DEFAULT NULL ,
  `HGNC` INT NULL DEFAULT NULL ,
  `AccessionNumber` VARCHAR(45) NULL DEFAULT NULL ,
  `PrimarySite` VARCHAR(50) NULL DEFAULT NULL ,
  `SiteSubtype` VARCHAR(50) NULL DEFAULT NULL ,
  `PrimaryHistology` VARCHAR(50) NULL DEFAULT NULL ,
  `HistologySubtype` VARCHAR(50) NULL DEFAULT NULL ,
  `MutationId` INT NULL DEFAULT NULL ,
  `MutationAA` VARCHAR(50) NULL DEFAULT NULL ,
  `MutationCDS` VARCHAR(45) NULL DEFAULT NULL ,
  `SomaticStatus` VARCHAR(45) NULL DEFAULT NULL ,
  `StartLocation` INT NOT NULL ,
  `EndLocation` INT NULL DEFAULT NULL ,
  `Strand` VARCHAR(45) NULL DEFAULT NULL ,
  `SAMPLE_ID` INT NULL DEFAULT NULL ,
  `VARIANT_ID` BIGINT(20) NOT NULL ,
  INDEX `fk_COSMIC_SAMPLE1` (`SAMPLE_ID` ASC) ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_COSMIC_VARIANT1` (`VARIANT_ID` ASC) ,
  CONSTRAINT `fk_COSMIC_SAMPLE1`
    FOREIGN KEY (`SAMPLE_ID` )
    REFERENCES `GVF_DB_Variant`.`SAMPLE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COSMIC_VARIANT1`
    FOREIGN KEY (`VARIANT_ID` )
    REFERENCES `GVF_DB_Variant`.`VARIANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
